-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.4 (64-bit) Schlumberger
-- User name   : Administrator
-- Date        : Friday, November 25 2022 09:30:30
-- Project     : EGG.pet
-- Generated ]

FWGR                                   -- Generated : Petrel

FWCT                                   -- Generated : Petrel

FRV                                    -- Generated : Petrel

FRS                                    -- Generated : Petrel

FVPR                                   -- Generated : Petrel

FVPT                                   -- Generated : Petrel

FVIR                                   -- Generated : Petrel

FVIT                                   -- Generated : Petrel

FPPW                                   -- Generated : Petrel

FPPO                                   -- Generated : Petrel

FPPG                                   -- Generated : Petrel

WBP5                                   -- Generated : Petrel
 /

WBP4                                   -- Generated : Petrel
 /

WBP                                    -- Generated : Petrel
 /

FWIP                                   -- Generated : Petrel

FOIPG                                  -- Generated : Petrel

FGIPL                                  -- Generated : Petrel

FOIP                                   -- Generated : Petrel

FOIPL                                  -- Generated : Petrel

FGIP                                   -- Generated : Petrel

FGIPG                                  -- Generated : Petrel

FOIR                                   -- Generated : Petrel

FOIT                                   -- Generated : Petrel

FGOR                                   -- Generated : Petrel

