-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.4 (64-bit) Schlumberger
-- User name   : Administrator
-- Date        : Friday, November 25 2022 09:30:30
-- Project     : EGG.pet
-- Generated ]

EQUIL                                  -- Generated : Petrel
          4000          400         5000            0         1000            0 1 0 0 /

RPTSOL
-- 
-- Initialisation Print Output
--
 RESTART=2 /

RSVD                                   -- Generated : Petrel
           860           48
          2000           92
          3500          181
          4000          216
  /

RPTRST                                 -- Generated : Petrel
  BASIC=3 FLOWS /

