-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.4 (64-bit) Schlumberger
-- User name   : Administrator
-- Date        : Friday, November 25 2022 09:30:30
-- Project     : EGG.pet
-- Generated ]

INIT                                   -- Generated : Petrel

GRIDFILE
  0 1 /

GRIDUNIT                               -- Generated : Petrel
  METRES /

MAPUNITS                               -- Generated : Petrel
  METRES /

MAPAXES                                -- Generated : Petrel
  0.00 -1184.00 0.00 -184.00 1000.00 -184.00 /

